version: "2.2"
services:
    composer:
        image: composer/composer
        container_name: composer
        command: [ "composer", "install" ]
        volumes:
            - ./docker/composer/conf/composer.json:/app/composer.json
            - ./docker/composer/conf/composer.lock:/app/composer.lock
            - ./docker/storage/vendor:/app/vendor

    app:
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
        container_name: app
        ports:
            - 80:80
            - 443:443
        depends_on:
            - ${DB_HOSTNAME}
            - self_signed_certificate
        volumes:
            - ./.env:/var/www/localhost/htdocs/.env:ro
            - ./src:/var/www/localhost/htdocs/src:ro
            - ./assets:/var/www/localhost/htdocs/assets:ro
            - ./docker/app/conf/.htaccess:/var/www/localhost/htdocs/.htaccess:ro
            - ./docker/app/conf/httpd.conf:/etc/apache2/httpd.conf:ro
            - ./docker/app/conf/settings.json:/var/www/localhost/htdocs/settings.json:ro
            - ./docker/app/conf/ssl.conf:/etc/apache2/conf.d/ssl.conf:ro
            - ./docker/storage/self_signed_certificate/server.crt:/etc/apache2/conf.d/server.crt
            - ./docker/storage/self_signed_certificate/server.key:/etc/apache2/conf.d/server.key
            - ./docker/storage/vendor:/var/www/localhost/htdocs/vendor:ro
            - ./public:/var/www/localhost/htdocs/public:ro

    self_signed_certificate:
        build:
            context: ./
            dockerfile: ./docker/self_signed_certificate/Dockerfile
        container_name: self_signed_certificate
        volumes:
            - ./docker/self_signed_certificate/conf:/app
            - ./docker/storage/self_signed_certificate:/out
    # Database
    db:
        image: mariadb
        container_name: ${DB_HOSTNAME}
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/storage/db/:/var/lib/mysql
            - ./docker/db/init/:/docker-entrypoint-initdb.d:ro
            - ./docker/db/conf.d/:/etc/mysql/:ro

    # Database frontend
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 42069:80
        environment:
            - PMA_HOST=${DB_HOSTNAME}
        depends_on:
            - ${DB_HOSTNAME}

    stripe:
        image: stripe/stripe-cli
        container_name: stripe-cli
        command: listen
        environment:
            - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
            - STRIPE_DEVICE_NAME=${USERNAME:-testing_host}
            - STRIPE_CLI_TELEMETRY_OPTOUT=true
        depends_on:
            - app
    # Workaround so developers can delete ./docker/storage
    volume-permissions-manager:
        image: alpine:latest
        command: sh -c "chmod -R 777 /storage && chown -R 1000:1000 /storage"
        volumes:
            - ./docker/storage/:/storage
        depends_on:
            - ${DB_HOSTNAME}
            - composer
