version: "2.2"
services:
    # Web server
    apache:
        build: .
        container_name: apache
        ports:
            - 80:80
            - 443:443
        depends_on:
            - ${DB_HOSTNAME}
        volumes:
            - ./private:/var/www/localhost/htdocs/private
            - ./public:/var/www/localhost/htdocs/public
            - ./js:/var/www/localhost/htdocs/js
            - ./translations:/var/www/localhost/htdocs/translations
            - ./css:/var/www/localhost/htdocs/css
            - ./img:/var/www/localhost/htdocs/img
            - ./assets:/var/www/localhost/htdocs/assets
            - ./library:/var/www/localhost/htdocs/library

    # Database
    mariadb:
        image: mariadb
        container_name: ${DB_HOSTNAME}
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/mariadb/storage:/var/lib/mysql
            - ./docker/mariadb/databases:/docker-entrypoint-initdb.d
            - ./docker/mariadb/conf.d/:/etc/mysql/

    # Database frontend
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 42069:80
        environment:
            - PMA_HOST=${DB_HOSTNAME}
        depends_on:
            - ${DB_HOSTNAME}

    stripe:
        image: stripe/stripe-cli
        container_name: stripe-cli
        command: listen
        environment:
            - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
            - STRIPE_DEVICE_NAME=${USERNAME:-testing_host}
            - STRIPE_CLI_TELEMETRY_OPTOUT=true
        depends_on:
            - apache

volumes:
    sessions: null
    storage: null
