version: "3.9"
services:
    # Web server
    apache:
        build: .
        container_name: apache
        ports:
            - 80:80
            - 443:443
        depends_on:
            - mariadb
        networks:
            - epstein-didnt-kill-himself
        volumes:
            - ./private:/var/www/localhost/htdocs/private
            - ./public:/var/www/localhost/htdocs/public
            - ./js:/var/www/localhost/htdocs/js
            - ./translations:/var/www/localhost/htdocs/translations
            - ./css:/var/www/localhost/htdocs/css
            - ./img:/var/www/localhost/htdocs/img
            - ./assets:/var/www/localhost/htdocs/assets
            - ./library:/var/www/localhost/htdocs/library
    # Database
    mariadb:
        image: mariadb
        container_name: mariadb
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_HOST=%
            - MARIADB_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=svommer_web
            - MYSQL_PASSWORD=testing_password
        volumes:
            - ./storage/mariadb:/var/lib/mysql
            - ./docker/mariadb/databases:/docker-entrypoint-initdb.d
            - ./docker/mariadb/conf.d/:/etc/mysql/
        networks:
            - epstein-didnt-kill-himself
    # Database frontend
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 42069:80
        environment:
            - PMA_HOST=mariadb
        depends_on:
            - mariadb
        networks:
            - epstein-didnt-kill-himself

networks:
    epstein-didnt-kill-himself:
        driver: bridge
        ipam:
            config:
                - subnet: 172.24.0.0/24

volumes:
    sessions: null
    storage: null
